import assert from "node:assert/strict";
import { createBaseline } from "../models/pregame/baseline.js";
import { americanImpliedProbability, compareMarketToBaseline, comparisonsForGame } from "../models/comparison.js";
import type { SportsMarketSnapshot } from "../types.js";
const runnerEventId = "RUNNER:CFB:2026-09-12:LSU:USC";
const baseline = createBaseline({ runnerEventId, target: "MONEYLINE", selection: "HOME", modelName: "runner-team-strength", modelVersion: "v1", sourceType: "RUNNER_MODEL", fairProbability: .6, confidence: .72, dataQuality: .81, inputs: ["team_efficiency_v2"], sourceTimestamp: "2026-09-12T17:00:00Z" }, "2026-09-12T17:00:01Z");
const market: SportsMarketSnapshot = { id: "odds:m", provider: "odds_api", providerEventId: "o1", runnerEventId, sport: "CFB", bookmakerKey: "book", bookmakerName: "Book", marketKey: "h2h", marketKind: "MONEYLINE", selection: "USC Trojans", teamSide: "HOME", americanPrice: 110, executable: true, status: "open", sourceTimestamp: "2026-09-12T17:01:00Z", sourceTimestampEstimated: false, receivedTimestamp: "2026-09-12T17:01:01Z", processedTimestamp: "2026-09-12T17:01:01Z", raw: {} };
assert.ok(Math.abs((americanImpliedProbability(110) ?? 0) - 0.476190476) < 0.000001);
const comparison = compareMarketToBaseline(baseline, market, "2026-09-12T17:01:02Z");
assert.equal(comparison.available, true);
assert.ok((comparison.probabilityEdge ?? 0) > .12);
assert.equal(comparison.confidence, .72);
assert.equal(comparison.dataQuality, .81);
assert.equal(comparison.executionAssessment, "NOT_EVALUATED");
assert.equal(compareMarketToBaseline(baseline, { ...market, executable: false }).available, false);
assert.equal(compareMarketToBaseline({ ...baseline, fairProbability: 2 }, market).available, false);
assert.deepEqual(comparisonsForGame(runnerEventId, [], [market])[0].suppressionReasons, ["RUNNER_PROJECTION_UNAVAILABLE"]);
assert.throws(() => createBaseline({ runnerEventId, target: "MONEYLINE", selection: "HOME", modelName: "baseline_market_implied_v0", modelVersion: "v0", sourceType: "RUNNER_MODEL", fairProbability: .5, confidence: .5, dataQuality: .5, inputs: ["sportsbook_price"], sourceTimestamp: "2026-09-12T17:00:00Z" }), /market-implied/);
console.log("baseline and model comparison tests passed");
