import assert from "node:assert/strict";
import { advanceDecisionWindow, analyzeLadder, classifyTrend, createDecisionWindow, createHalftimePacket, estimateRemainingPossessions, impliedProbability, noVigProbabilities, projectFootballTotals, scoringConversionSuppression, sourceSynchronization } from "../totals/engine.js";
import { mapProviderTotalsMarket, normalizeTotalsMarketType } from "../totals/market-mapper.js";
import type { FootballTotalsInputs, TotalsMarketSnapshot } from "../totals/types.js";
import { replayTotals } from "../totals/replay.js";

const input: FootballTotalsInputs = { runnerEventId:"RUNNER:NFL:2026-09-05:DAL:PHI", timestamp:"2026-09-05T20:00:05Z", sourceTimestamp:"2026-09-05T20:00:04Z", period:2, clockSecondsRemaining:600, currentHomePoints:10, currentAwayPoints:7, possession:"HOME", drivesCompleted:10, playsPerDrive:6, secondsPerPlay:25, homeObservedPointsPerDrive:2.2, awayObservedPointsPerDrive:1.7, homePregamePointsPerDrive:2, awayPregamePointsPerDrive:1.8, homeScoringOpportunities:4, awayScoringOpportunities:3, homeRedZoneEntries:2, awayRedZoneEntries:2, homeExplosivePlays:3, awayExplosivePlays:1, homePressureAllowed:0.2, awayPressureAllowed:0.4, opportunityPointsExpectation:24, actualOpportunityPoints:17, tempoDirection:"RISING", gameRegime:"BALANCED" };
const market: TotalsMarketSnapshot = { id:"book:total", runnerEventId:input.runnerEventId, provider:"odds_api", bookmaker:"book", marketKey:"totals", marketType:"GAME_TOTAL", selection:"OVER", line:41.5, price:-110, timestamp:"2026-09-05T20:00:04Z" };

assert.equal(normalizeTotalsMarketType("totals"), "GAME_TOTAL");
assert.equal(normalizeTotalsMarketType("q3_totals"), "THIRD_QUARTER_TOTAL");
assert.equal(normalizeTotalsMarketType("q3_totals", "PHI"), "THIRD_QUARTER_TEAM_TOTAL");
assert.equal(mapProviderTotalsMarket({ key:"totals",name:"Over",point:41.5,price:-110 }, { provider:"odds_api",runnerEventId:input.runnerEventId,receivedTimestamp:input.timestamp })?.selection,"OVER");
assert.ok(estimateRemainingPossessions(input).total > 0);
assert.ok((scoringConversionSuppression(input)?.conversionSuppression ?? 0) > 0);
const result=projectFootballTotals(input);
assert.equal(result.projections.length,3);
assert.equal(result.flow.currentScoreTotal,17);
assert.ok((result.flow.projectedFinalTotal??0)>17);
assert.equal(result.flow.inputs.modelVersion,"football-heuristic-v1");
assert.equal(classifyTrend(49),"NEUTRAL");
assert.equal(classifyTrend(85),"STRONG_ACTION_WINDOW_CANDIDATE");
const sync=sourceSynchronization(input,market,"2026-09-05T20:00:05Z");
assert.equal(sync.conflicts.length,0);
const gameProjection=result.projections[0];
const over=createDecisionWindow(market,gameProjection,{over:80,under:20},input,"2026-09-05T20:00:05Z");
assert.notEqual(over.status,"SUPPRESSED");
const wrongUnder=createDecisionWindow({...market,selection:"UNDER"},gameProjection,{over:80,under:80},input,"2026-09-05T20:00:05Z");
assert.equal(wrongUnder.status,"SUPPRESSED");
assert.ok(wrongUnder.suppressions?.includes("LOW_EDGE"));
const decayed=advanceDecisionWindow(over,0.1,"2026-09-05T20:00:06Z");
assert.equal(decayed.status,"DECAYING");
assert.ok((decayed.informationDecayIndex??1)<0.5);
const stale=createDecisionWindow({...market,timestamp:"2026-09-05T19:00:00Z"},gameProjection,{over:80,under:20},input,"2026-09-05T20:00:05Z");
assert.ok(stale.suppressions?.includes("STALE_MARKET_FEED"));
assert.equal(createHalftimePacket({...input,clockSecondsRemaining:0},result.projections).score.home,10);
assert.equal(analyzeLadder([{...market,line:20.5},{...market,id:"2",line:27.5}],7)[1].likelyScoreCountRequired,3);
assert.ok(impliedProbability(-110)>0.52);
assert.ok(Math.abs(noVigProbabilities(-110,-110).overNoVig-0.5)<0.001);
assert.deepEqual(replayTotals([{input,markets:[market]}]),replayTotals([{input,markets:[market]}]));
console.log("totals engine tests passed");
