import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const REPORT = [".runner", "research", "combos", "2026-10-02-tonight-ncaaf-wnba-band-combos.md"];
const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);

export function renderComboResearch(root = process.cwd()): string {
  const path = join(root, ...REPORT);
  const source = readFileSync(path, "utf8");
  const modified = statSync(path).mtime.toISOString();
  const sections = [...source.matchAll(/^### (C\d{2}) - (\d+) legs - hypothetical product (x[\d.]+).*$/gm)];
  const cards = sections.map((match, index) => {
    const body = source.slice(match.index! + match[0].length, sections[index + 1]?.index ?? source.indexOf("\n## 6.", match.index!));
    const rows = [...body.matchAll(/^\| (\d+) \| `([^`]+)` \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \|$/gm)];
    const legs = rows.map(row => `<tr><td>${escape(row[2].split(":").slice(-2).join(" @ "))}</td><td>${escape(row[3].trim())}</td><td>${escape(row[4].trim())}</td><td>${escape(row[5].trim())}</td><td>${escape(row[6].trim())}</td><td>${escape(row[8].trim())}</td><td>${escape(row[10].trim())}</td></tr>`).join("");
    const books = new Set(rows.map(row => row[8].trim()));
    const operatorStatus = books.size > 1 ? "Multiple operators; no single venue offers these recorded leg prices together." : "One recorded operator; combo acceptance and offered price unverified.";
    return `<article class="card" data-legs="${match[2]}"><header><span class="id">${match[1]}</span><strong>${match[2]} legs</strong><span class="product">${match[3]} illustrative product</span></header><div class="scroll"><table><thead><tr><th>Event</th><th>Period</th><th>Market</th><th>Selection</th><th>Leg price</th><th>Book</th><th>Receipt UTC</th></tr></thead><tbody>${legs}</tbody></table></div><p>Offered combo price, fees, limits, settlement, joint probability and edge: <b>UNKNOWN</b>. ${operatorStatus}</p></article>`;
  }).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="refresh" content="30"><title>Runner | Tonight's combo research</title><style>
    :root{color-scheme:dark;font:15px system-ui,sans-serif;background:#090f1b;color:#e8edf6}*{box-sizing:border-box}body{margin:0}main{max-width:1440px;margin:auto;padding:28px 20px 60px}a{color:#9ecbff}.eyebrow{color:#7db3f4;font-size:12px;letter-spacing:.18em;font-weight:700;text-transform:uppercase}h1{font-size:clamp(30px,4vw,52px);margin:8px 0}.sub{color:#aeb9c9;line-height:1.5}.notice{border:1px solid #b58a37;background:#332714;color:#ffe7a6;border-radius:12px;padding:16px;margin:20px 0}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:20px 0}.metric,.card{border:1px solid #28374e;background:#111b2b;border-radius:12px}.metric{padding:16px}.metric b{display:block;font-size:24px}.metric span{color:#aeb9c9;font-size:12px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:24px 0}.toolbar button{background:#1d3454;color:#fff;border:1px solid #4a719d;border-radius:7px;padding:9px 15px;cursor:pointer}.toolbar button[aria-pressed=true]{background:#3e72ad}.card{margin:14px 0;overflow:hidden}.card header{display:flex;align-items:center;gap:16px;padding:16px 18px}.id{background:#b7293e;color:#fff;border-radius:5px;padding:5px 9px;font-weight:800}.product{margin-left:auto;color:#aeb9c9}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;min-width:850px}th,td{text-align:left;padding:10px 14px;border-top:1px solid #26354a}th{font-size:11px;text-transform:uppercase;color:#9eb1ca}td{font-size:13px}.card p{color:#e1bf78;padding:0 18px 16px;margin:14px 0 0}.meta{font-size:12px;color:#8fa2ba}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}.card header{flex-wrap:wrap}.product{margin-left:0}}
  </style></head><body><main><a href="/dashboard">← Runner Control Center</a><div class="eyebrow">REPOSITORY RESEARCH · 2026-10-02</div><h1>Tonight's combo worksheet</h1><p class="sub">NCAAF and WNBA observations from the saved report. This page rereads the repo file every 30 seconds; it does not fetch live sportsbook quotes.</p><div class="notice"><b>RESEARCH ONLY · NOT PLACED</b><br>No offered joint price, validated joint probability, fees, available size or verified settlement terms. No verified Runner edge. Operator compatibility is shown per combination.</div><div class="metrics"><div class="metric"><b>${sections.length}</b><span>candidate combinations</span></div><div class="metric"><b>1.18–1.60×</b><span>recorded leg price band</span></div><div class="metric"><b>0</b><span>verified executable combos</span></div><div class="metric"><b>UNKNOWN</b><span>joint edge</span></div></div><p class="meta">Source: ${escape(REPORT.join("/"))} · File modified ${escape(modified)} · BettingPros quote timestamps: NOT SHOWN; table times are browser receipts.</p><div class="toolbar"><span>Show:</span><button type="button" data-filter="all" aria-pressed="true">All</button><button type="button" data-filter="2" aria-pressed="false">2 legs</button><button type="button" data-filter="3" aria-pressed="false">3 legs</button><button type="button" data-filter="4" aria-pressed="false">4 legs</button><span id="count" role="status"></span></div><div id="cards">${cards}</div><p class="meta">For source caveats, Kalshi comparison and invalidation criteria, read the <a href="/research/combos/source">source worksheet</a>.</p></main><script>const buttons=[...document.querySelectorAll('[data-filter]')],cards=[...document.querySelectorAll('.card')];function select(value){buttons.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.filter===value)));cards.forEach(card=>card.hidden=value!=='all'&&card.dataset.legs!==value);document.querySelector('#count').textContent=cards.filter(card=>!card.hidden).length+' shown'}buttons.forEach(button=>button.addEventListener('click',()=>select(button.dataset.filter)));select('all');</script></body></html>`;
}

export function readComboResearchSource(root = process.cwd()): string {
  return readFileSync(join(root, ...REPORT), "utf8");
}
